app.name: product
product.count.max: 100
app.operator.name: ORDR
app.topic: topic_product_order
app:
  logging:
    request: true
    response: true
logging:
  level:
    com:
      sharma:
        nks:
          products:
            management: DEBUG

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    password: pass
    username: sa
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/testdb3  #testdb
  h2:
    console:
      path: /h2
      enabled: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
